### ISSUE TITLE
`expmeter_mean_winsor` and `expmeter_rms_winsor` undefined in catch exception

### ISSUE THREAD

**Issue by hematthi** [RvSpectML/EchelleInstruments.jl#50]
https://github.com/RvSpectML/EchelleInstruments.jl/blob/98d5a94f72a863b2cd97cb0b582265e3d4dca96b/src/neid/io.jl#L146-L152

**Comment by eford** [comment]
Fixed in [fd41a59a](https://github.com/RvSpectML/EchelleInstruments.jl/commit/fadbe7793b4d35152d0312a9bf29981dfd41a59a)
