### ISSUE TITLE
no implementation of `read_data` with these arguments

### ISSUE THREAD

**Issue by hematthi** [RvSpectML/EchelleInstruments.jl#51]
https://github.com/RvSpectML/EchelleInstruments.jl/blob/98d5a94f72a863b2cd97cb0b582265e3d4dca96b/src/neid/io.jl#L261

Assuming `fn` is a String

**Comment by eford** [comment]
Fixed in [fadbe7793b4d35152d0312a9bf29981dfd41a59a](https://github.com/RvSpectML/EchelleInstruments.jl/commit/fadbe7793b4d35152d0312a9bf29981dfd41a59a)
